services:
  - type: web
    name: dqm-backend
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    rootDir: ./